setwd("~/Copy/OnlineCourses/CourseraDataScience/Course2_RProgramming")
hw1_data <- read.csv("hw1_data.csv")
head(hw1_data)
dim(hw1_data)
tail(hw1_data, n=2)
summary(hw1_data[,1])
summary(subset(hw1_data, hw1_data$Ozone > 31 & hw1_data$Temp > 90))
summary(subset(hw1_data, hw1_data$Month == 6))
summary(subset(hw1_data, hw1_data$Month == 5))